In [40]:
# importing libraries 
import numpy as np 
import pandas as pd 
import warnings 
warnings.filterwarnings(action="ignore")

In [41]:
df=pd.read_excel(r"C:\Users\Lenovo\Documents\My Projects only\Health_care_sem8\dataset\healthcare_emotion_dataset_15000.xlsx")

In [42]:
df.describe

<bound method NDFrame.describe of                                             journal_text ambience_type  \
0            I kept overthinking and felt uncomfortable.       crowded
1      I stayed disciplined and energetic throughout ...          home
2        I struggled to manage my emotions and workload.        nature
3         My thoughts were scattered and I felt anxious.        office
4        I experienced both motivation and stress today.       library
...                                                  ...           ...
14995    I struggled to manage my emotions and workload.          home
14996  I had a balanced day and felt emotionally stable.       crowded
14997  I could not focus and felt uneasy throughout t...        nature
14998      I felt normal and stable for most of the day.       library
14999    Nothing significant happened today emotionally.         quiet

       duration_min  sleep_hours  energy_level stress_level time_of_day  \
0                90          5.9             4         High     Evening
1                21          8.2             8          Low   Afternoon
2               123          5.6             3     Moderate     Evening
3               101          6.2             3          Low     Morning
4                50          6.5             4     Moderate       Night
...             ...          ...           ...          ...         ...
14995           127          5.4             2     Moderate     Evening
14996           111          7.4             8          Low     Morning
14997           157          4.4             3     Moderate     Evening
14998            22          7.0             5     Moderate   Afternoon
14999           102          7.0             4     Moderate     Evening

      previous_day_mood face_emotion_hint reflection_quality emotional_state
0                normal           focused                low        restless
1                normal           focused               high         focused
2                   sad           focused                low     overwhelmed
3                   sad             smile               high        restless
4             motivated           focused                low           mixed
...                 ...               ...                ...             ...
14995            normal           anxiety                low     overwhelmed
14996           anxious           anxiety             medium            calm
14997         motivated           focused               high        restless
14998             happy             smile                low         neutral
14999            normal             smile               high         neutral

[15000 rows x 11 columns]>

In [43]:
df.head(2)

,journal_text,ambience_type,duration_min,sleep_hours,energy_level,stress_level,time_of_day,previous_day_mood,face_emotion_hint,reflection_quality,emotional_state
0,I kept overthinking and felt uncomfortable.,crowded,90,5.9,4,High,Evening,normal,focused,low,restless
1,I stayed disciplined and energetic throughout ...,home,21,8.2,8,Low,Afternoon,normal,focused,high,focused

In [44]:
df=df.drop("face_emotion_hint" , axis = 1)

In [45]:
df.isnull().sum()

journal_text          0
ambience_type         0
duration_min          0
sleep_hours           0
energy_level          0
stress_level          0
time_of_day           0
previous_day_mood     0
reflection_quality    0
emotional_state       0
dtype: int64

In [46]:
df.emotional_state.value_counts()

emotional_state
overwhelmed    2597
calm           2531
restless       2527
mixed          2480
focused        2439
neutral        2426
Name: count, dtype: int64

In [47]:
# Lable Encoding Target variable 
from sklearn.preprocessing import LabelEncoder
le_emotional_state = LabelEncoder()
le_ambience_type = LabelEncoder()
le_stress_level = LabelEncoder()
le_time_of_day = LabelEncoder()
le_previous_day_mood = LabelEncoder()
le_reflection_quality = LabelEncoder()

In [48]:
df['emotional_state']=le_emotional_state.fit_transform(df['emotional_state'] )
df['ambience_type']=le_ambience_type.fit_transform(df['ambience_type'])
df['stress_level']=le_stress_level.fit_transform(df['stress_level'])
df['time_of_day']=le_time_of_day.fit_transform(df['time_of_day'])
df['previous_day_mood']=le_previous_day_mood.fit_transform(df['previous_day_mood'])
df['reflection_quality']=le_reflection_quality.fit_transform(df['reflection_quality'])

In [49]:
df[:2]

,journal_text,ambience_type,duration_min,sleep_hours,energy_level,stress_level,time_of_day,previous_day_mood,reflection_quality,emotional_state
0,I kept overthinking and felt uncomfortable.,0,90,5.9,4,0,1,3,1,5
1,I stayed disciplined and energetic throughout ...,1,21,8.2,8,1,0,3,0,1

In [50]:
jt=df.journal_text

In [51]:
# Importing text vectorizer for "journal_text" processing 
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
tfidf = TfidfVectorizer(max_features=500 , stop_words='english' )

In [53]:
text_features = tfidf.fit_transform(jt)

In [54]:
text_df = pd.DataFrame(text_features.toarray() , columns = tfidf.get_feature_names_out())

In [55]:
text_df

,anxious,average,balanced,changes,comfortably,completed,concentration,day,difficult,disciplined,...,stress,stressed,struggled,tasks,thoughts,today,uncomfortable,uneasy,work,workload
0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.557651,0.000000,0.0,0.000000
1,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.323472,0.0,0.546311,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
2,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.520805,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.520805
3,0.483028,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.58803,0.000000,0.000000,0.000000,0.0,0.000000
4,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.546523,0.0,0.000000,0.0,0.00000,0.322393,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.520805,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.520805
14996,0.000000,0.0,0.585337,0.0,0.0,0.0,0.0,0.343447,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
14997,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.365204,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.625889,0.0,0.000000
14998,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.391267,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
14999,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.339377,0.000000,0.000000,0.0,0.000000

In [56]:
df = df.drop(columns=['journal_text'])

In [57]:
df = pd.concat([df.reset_index(drop=True), text_df.reset_index(drop=True)], axis=1)

In [58]:
df

,ambience_type,duration_min,sleep_hours,energy_level,stress_level,time_of_day,previous_day_mood,reflection_quality,emotional_state,anxious,...,stress,stressed,struggled,tasks,thoughts,today,uncomfortable,uneasy,work,workload
0,0,90,5.9,4,0,1,3,1,5,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.557651,0.000000,0.0,0.000000
1,1,21,8.2,8,1,0,3,0,1,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
2,3,123,5.6,3,2,1,4,1,4,0.000000,...,0.000000,0.0,0.520805,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.520805
3,4,101,6.2,3,1,2,4,0,5,0.483028,...,0.000000,0.0,0.000000,0.0,0.58803,0.000000,0.000000,0.000000,0.0,0.000000
4,2,50,6.5,4,2,3,2,1,2,0.000000,...,0.546523,0.0,0.000000,0.0,0.00000,0.322393,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,1,127,5.4,2,2,1,3,1,4,0.000000,...,0.000000,0.0,0.520805,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.520805
14996,0,111,7.4,8,1,2,0,2,0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
14997,3,157,4.4,3,2,1,2,0,5,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.625889,0.0,0.000000
14998,2,22,7.0,5,2,0,1,1,3,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000
14999,5,102,7.0,4,2,1,3,0,3,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.339377,0.000000,0.000000,0.0,0.000000

Splitting data for different target variables and training models

In [59]:
from xgboost import XGBClassifier

In [60]:
em_model = XGBClassifier(n_estimators=200,max_depth=5,learning_rate=0.1,)

Modeling for Emotional state prediction

In [61]:
# Dividing data into Input and Target columns 
x_em = df.drop(["emotional_state"] , axis = 1)
y_em = df.emotional_state

In [62]:
# Importing train test split library 
from sklearn.model_selection import train_test_split

In [63]:
x_train , x_test , y_train , y_test = train_test_split(x_em , y_em , test_size=0.2 , random_state=42)

In [64]:
# Model training 
em_model.fit(x_train , y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [65]:
y_pred = em_model.predict(x_test)

In [66]:
# Importing classification report 
from sklearn.metrics import classification_report

In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       477
           1       1.00      1.00      1.00       442
           2       1.00      1.00      1.00       535
           3       1.00      1.00      1.00       513
           4       1.00      1.00      1.00       504
           5       1.00      1.00      1.00       529

    accuracy                           1.00      3000
   macro avg       1.00      1.00      1.00      3000
weighted avg       1.00      1.00      1.00      3000

----

Dumping Models

In [68]:
import joblib

In [69]:
joblib.dump(em_model , "emotion_model.pkl")

['emotion_model.pkl']

In [70]:
joblib.dump(tfidf , "vectorizer.pkl")

['vectorizer.pkl']

In [71]:
joblib.dump(le_emotional_state , "le_emotional_state.pkl")

['le_emotional_state.pkl']

In [72]:
joblib.dump(le_ambience_type , "le_ambience_type.pkl")

['le_ambience_type.pkl']

In [73]:
joblib.dump(le_stress_level , "le_stress_level.pkl")

['le_stress_level.pkl']

In [74]:
joblib.dump(le_time_of_day , "le_time_of_day.pkl")

['le_time_of_day.pkl']

In [75]:
joblib.dump(le_previous_day_mood , "le_previous_day_mood.pkl")

['le_previous_day_mood.pkl']

In [76]:
joblib.dump(le_reflection_quality , "le_reflection_quality.pkl")

['le_reflection_quality.pkl']